
import { z } from "zod";

export const CreateCaseReportValidationZodSchema = z.object({
  title: z
    .string()
    .min(1, "Report Title Is Required")
    .max(200, "Report Title Cannot Exceed 200 Characters"),

  summary: z
    .string()
    .max(5000, "Report Summary Cannot Exceed 5000 Characters")
    .optional(),

  reportUrl: z
    .string()
    .url("Report URL Must Be A Valid URL")
    .optional(),

  reportPublicId: z
    .string()
    .min(1, "Report Public Id Cannot Be Empty")
    .optional(),

  generatedBy: z
    .string()
    .min(1, "Generated By Cannot Be Empty")
    .optional(),

});

export const UpdateCaseReportValidationZodSchema = z.object({
  title: z
    .string()
    .min(1, "Report Title Cannot Be Empty")
    .max(200, "Report Title Cannot Exceed 200 Characters")
    .optional(),

  summary: z
    .string()
    .max(5000, "Report Summary Cannot Exceed 5000 Characters")
    .optional(),

  reportUrl: z
    .string()
    .url("Report URL Must Be A Valid URL")
    .optional(),

  reportPublicId: z
    .string()
    .min(1, "Report Public Id Cannot Be Empty")
    .optional(),
});

